    const TRANSLATIONS = {
        "Meet": "Rencontre avec",
        "and Friends": "et ses amis",
        "near": "près de",
        "at": "à",
        "Princess Pavilion": "Pavillon des Princesses",
        "Hero Training Center": "Hero Training Center",
        "Town Square": "Town Square",
        "Boarding House": "Boarding House",
        "Casey's Corner": "Casey's Corner",
        "Phantom Manor": "Phantom Manor",
        "Frontierland": "Frontierland",
        "Adventureland": "Adventureland",
        "Fantasyland": "Fantasyland",
        "Discoveryland": "Discoveryland",
        "Toon Studio": "Toon Studio",
        "Production Courtyard": "Production Courtyard",
        "Front Lot": "Front Lot",
        "Avengers Campus": "Avengers Campus",
        "Mickey Mouse": "Mickey",
        "Minnie Mouse": "Minnie",
        "Donald Duck": "Donald",
        "Daisy Duck": "Daisy",
        "Goofy": "Dingo",
        "Chip and Dale": "Tic et Tac",
        "Winnie the Pooh": "Winnie l'Ourson",
        "Stitch": "Stitch",
        "Captain Hook": "Capitaine Crochet",
        "Jafar": "Jafar",
        "Genie": "Génie",
        "Aladdin": "Aladdin",
        "Jack Skellington": "Jack Skellington",
        "Darth Vader": "Dark Vador",
        "a Character from The Lion King":"un personnage du Roi Lion",
        "Encounter The Mandalorian":"Rencontrez le Mandalorian",
        "Disney Characters":"Disney Characters",
        "Disney Characters":"Personnages Disney",
        "Starport":"Starport - Rencontrez un personnage Star Wars",
        "the Characters of Alice in Wonderland":"Un personnage d'Alice aux Pays des Merveilles",
        "The White Rabbit":"Le Lapin Blanc",
        "Tigger":"Tigrou",
        "Winnie l'Ourson or friends":"Winnie l'Ourson ou ses amis"
    };